# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: playlist.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eplaylist.proto\"&\n\x15\x43reatePlaylistRequest\x12\r\n\x05title\x18\x01 \x01(\t\"$\n\x16\x43reatePlaylistResponse\x12\n\n\x02id\x18\x01 \x01(\x0c\x32O\n\x08PlayList\x12\x43\n\x0e\x43reatePlaylist\x12\x16.CreatePlaylistRequest\x1a\x17.CreatePlaylistResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'playlist_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEPLAYLISTREQUEST._serialized_start=18
  _CREATEPLAYLISTREQUEST._serialized_end=56
  _CREATEPLAYLISTRESPONSE._serialized_start=58
  _CREATEPLAYLISTRESPONSE._serialized_end=94
  _PLAYLIST._serialized_start=96
  _PLAYLIST._serialized_end=175
# @@protoc_insertion_point(module_scope)
